language: python
sudo: false

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.8.6"
  - DJANGO="django==1.9"

install:
  - pip install $DJANGO jinja2 "django-pipeline<1.6" pytz

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.9"

script:
  - cd testing && python runtests.py

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
